name: CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.1', '3.2']
    name: Ruby ${{ matrix.ruby }}
    
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server
  
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and test

        run: |
          gem update --system
          sudo apt-get update
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec
